experiment_name: "telco_churn_cleaned"
random_state: 42

data:
  source: "data/telco_cleaned.csv"  # CSV dosyanın gerçek yolu
  test_size: 0.2

rebalancing:
  use_oversampling: True

thresholds:
  production_min_pr_auc: 0.65
  production_min_roc_auc: 0.70
  production_min_recall: 0.60

registry:
  model_name: "telco_churn_classifier_cleaned"

model:
  main:
    type: "xgboost"  # veya "randomforest"
